#!/usr/bin/env sh

# Check the number of arguments
if [[ $# -eq 1 ]]; then
  commitMsg="$1"
else
  echo "Usage: $0 \"commit message\""
  exit 1
fi

# Check if you are in a Git repository
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    # Get the current branch name
    branch_name=$(git rev-parse --abbrev-ref HEAD)
    echo "Current branch: $branch_name"


    if echo "$branch_name" | grep -q -E ".*\/(PICAP|CLOUDOPS)-[0-9]+"; then
        story=$(echo "$branch_name" | sed -E -n 's/.*\/(PICAP|CLOUDOPS)-([0-9]+).*/\1-\2/p')
        if [ -n "$story" ]; then
            echo "Story number: $story"
            
            commitMsg="$commitMsg [$story]"
        fi
        
    else
      # Don't do anything special with the story suffix.
      echo "Branch name '$branch_name' does not match the story pattern."
    fi
else
    echo "not in a Git repository."
    exit 2
fi

echo "The commit message is '${commitMsg}'"

git add .
git commit -m "${commitMsg}"
git push

