#!/usr/bin/env zsh

# Check the number of arguments
if [[ $# -eq 1 ]]; then
  commitMsg="docs: $1"
else
  echo "Usage: $0 \"commit message\""
  exit 1
fi

# Call the "in" script with the modified commit message
./in "$commitMsg"
