#!/usr/bin/env sh

# Check the number of arguments
if [[ $# -eq 1 ]]; then
  commitMsg="test: $1"
elif [[ $# -eq 2 ]]; then
  commitMsg="test($2): $1"
else
  echo "Usage: $0 \"commit message\" [scope]"
  exit 1
fi

# Call the "up" script with the modified commit message
up "${commitMsg}"
